import http from 'node:http';
import { readFile, writeFile } from 'node:fs/promises';
import { extname, join } from 'node:path';
import { chromium } from 'playwright-core';
const ROOT='/workspace/templategeneratorintegrationdemo', S='/tmp/claude-0/-home-user-templateGenerator/c95d35fa-9196-564b-ae9d-35ddfaace90e/scratchpad';
const MIME={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml'};
const srv=await new Promise(r=>{const s=http.createServer(async(req,res)=>{const file=join(ROOT,decodeURIComponent(req.url.split('?')[0]).replace(/^\//,'')||'index.html');try{const b=await readFile(file);res.writeHead(200,{'Content-Type':MIME[extname(file)]||'application/octet-stream'});res.end(b);}catch{res.writeHead(404);res.end();}});s.listen(0,'127.0.0.1',()=>r(s));});
const base=`http://127.0.0.1:${srv.address().port}`;
const design = process.argv[2] || 'studionorth';
const html=await readFile(`${S}/${design}.html`,'utf-8');
const browser=await chromium.launch({executablePath:'/opt/pw-browsers/chromium',headless:true});
const page=await(await browser.newContext()).newPage();
page.on('console',m=>{const t=m.text();if(/raster|fallback|fail/i.test(t))console.log('  console:',t.slice(0,120));});
await page.goto(`${base}/generator/index.html`); await page.waitForTimeout(700);
await page.evaluate((h)=>{lastPayload={templateType:'Business Card',width:3.5,height:2,unit:'in',doubleSided:false,businessName:'X'};generatedHtml=h;document.getElementById('emptyState').classList.add('hidden');document.getElementById('resultState').classList.remove('hidden');const f=document.getElementById('previewFrame');f.style.width='360px';f.style.height='560px';f.srcdoc=h;},html);
await page.waitForTimeout(1600);
const conv=await page.evaluate(async()=>{const{template}=await window.SMPPush.convertCurrentDesign();const objs=template.pages[0].canvasData.objects;const counts={};objs.forEach(o=>{const k=o.type+(o.sterlingType?'/'+o.sterlingType:'');counts[k]=(counts[k]||0)+1;});return{counts,total:objs.length};});
console.log(`[${design}] objects:`, JSON.stringify(conv.counts));
const [real]=await Promise.all([page.context().waitForEvent('page'),page.click('#pushToDesignerBtn')]);
await real.waitForLoadState('domcontentloaded'); await real.setViewportSize({width:1400,height:820}); await real.waitForTimeout(6500);
await real.screenshot({path:`${S}/tier1-${design}.png`});
console.log(`  screenshot: tier1-${design}.png`);
await browser.close(); srv.close();
